project:
  type: website
  output-dir: _site
  resources:
    - playground.html
    - api-explorer.html

website:
  title: "panel-live Quarto Test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: examples.qmd
        text: Examples
      - href: pre-rendering.qmd
        text: Pre-Rendering
      - href: versions.qmd
        text: Versions
      - href: playground.html
        text: Playground
      - href: api-explorer.html
        text: API Explorer

format:
  html:
    theme: cosmo

filters:
  - panel-live

panel-live:
  pyodide-version: "v0.28.2"
  panel-version: "1.8.7"
  bokeh-version: "3.8.2"
  pre-render: true
  default-auto-run: false
